# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=60)),
                ('anulado', models.BooleanField(default=True)),
                ('cuentaEmpresa', models.IntegerField(default=170)),
                ('cuentaCliente', models.IntegerField(default=170)),
                ('cuentaGanancia', models.IntegerField(default=170)),
                ('cuentaVenta', models.IntegerField(default=170)),
                ('entregadoA', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha', models.DateTimeField(blank=True, max_length=60, null=True)),
                ('sucursal', models.IntegerField(default=170)),
                ('total', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
