# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('perfi', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('sucursal', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'UsuarioCajero',
                'verbose_name_plural': 'UsuarioCajeros',
            },
        ),
    ]
